site_name: Image Classification App Boilerplate
repo_url: https://github.com/smaranjitghose/img_ai_app_boilerplate

nav:
    - Home: index.md
    - Getting Started: getting_started.md

theme: 
    name: 'material'
    logo: 'images/favicon.png'
    favicon: 'images/favicon.png'
    palette:
        scheme: slate
        primary: deep purple
    font:
        text: Poppins
    features:
        - navigation.expand
        - searcn.highlight

plugins:
  - search

google_analytics:
  - UA-XXXXXXXX-X
  - auto

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
